name: Terraform Pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check formatting
        run: terraform fmt -check -recursive

      - name: Initialize Terraform
        run: terraform init
